image: python:3.7

test:
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - pytest -v --cov=. --cov-report term --cov-report=html:coverage --strict-markers
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/ public/coverage/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
