name: Update survey health files
on:
  schedule:
    - cron:  '30 10 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test with tox
      run: |
        pip install tox
        tox -e health_update
    - name: Create Survey Update Commit
      uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Updating survey health files
        # Optional name of the branch the commit should be pushed to
        # Required if Action is used in Workflow listening to the `pull_request` event
        branch: solution-survey-cron

        # Optional glob pattern of files which should be added to the commit
        file_pattern: data/health/*

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Survey Health Cron Job
        commit_user_email: drawdownbot@decarbon.earth
        commit_author: DrawdownBot <drawdownbot@decarbon.earth>
